// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import services "github.com/dmibod/kanban/shared/services"

// CardServiceFactory is an autogenerated mock type for the CardServiceFactory type
type CardServiceFactory struct {
	mock.Mock
}

// CreateCardService provides a mock function with given fields: _a0
func (_m *CardServiceFactory) CreateCardService(_a0 context.Context) services.CardService {
	ret := _m.Called(_a0)

	var r0 services.CardService
	if rf, ok := ret.Get(0).(func(context.Context) services.CardService); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.CardService)
		}
	}

	return r0
}
