version: '3'
services:
  bus:
    image: nats-streaming
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  app:
    image: dmibod/kanban-monolith
    ports:
      - '8080:3001'
    environment:
      - BUS_URL=nats://bus:4222
      - MGO_URL=db:27017
    depends_on:
      - bus
      - db
networks:
  default:
    driver: bridge