version: '3'
services:
  nats:
    image: nats-streaming
    networks:
      - kanban
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - kanban
  app:
    image: dmibod/kanban-monolith
    ports:
      - '8080:8080'
    environment:
      - MUX_PORT=8080
      - BUS_URL=nats://kanban:4222
      - MGO_URL=kanban:27017
    networks:
      - kanban
    depends_on:
      - nats
      - mongo
networks:
  kanban:
