version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: ls ~/project/
      - run: go test ~/project/kanban/query/test -race
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"      