version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: mkdir /tmp/test-reports      
      - run: gotestsum --junitfile /tmp/test-reports/query-tests.xml -- ~/project/query/test
      - run: gotestsum --junitfile /tmp/test-reports/update-tests.xml -- ~/project/update/test
      - store_test_results:
          path: /tmp/test-reports
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"      