version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: ls
      - run: gotestsum --junitfile test-results -- ~/project/query/test
      - run: ls
      - run: ls /tmp/
      - store_test_results:
          path: /tmp/test-results      
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"      