version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: mkdir /tmp/test-reports      
      - run: gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - run: cat /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"      