version: '3'
services:
  bus:
    image: nats-streaming
    ports:
      - '4222:4222'
  db:
    image: mongo:4.0.5
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
networks:
  default:
    driver: bridge