// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import kernel "github.com/dmibod/kanban/shared/kernel"
import mock "github.com/stretchr/testify/mock"
import services "github.com/dmibod/kanban/shared/services"

// CardService is an autogenerated mock type for the CardService type
type CardService struct {
	mock.Mock
}

// CreateCard provides a mock function with given fields: _a0
func (_m *CardService) CreateCard(_a0 *services.CardPayload) (kernel.Id, error) {
	ret := _m.Called(_a0)

	var r0 kernel.Id
	if rf, ok := ret.Get(0).(func(*services.CardPayload) kernel.Id); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(kernel.Id)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*services.CardPayload) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
