// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import kernel "github.com/dmibod/kanban/shared/kernel"
import mock "github.com/stretchr/testify/mock"
import services "github.com/dmibod/kanban/shared/services"

// CardService is an autogenerated mock type for the CardService type
type CardService struct {
	mock.Mock
}

// CreateCard provides a mock function with given fields: _a0, _a1
func (_m *CardService) CreateCard(_a0 context.Context, _a1 *services.CardPayload) (kernel.Id, error) {
	ret := _m.Called(_a0, _a1)

	var r0 kernel.Id
	if rf, ok := ret.Get(0).(func(context.Context, *services.CardPayload) kernel.Id); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(kernel.Id)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *services.CardPayload) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardByID provides a mock function with given fields: _a0, _a1
func (_m *CardService) GetCardByID(_a0 context.Context, _a1 kernel.Id) (*services.CardModel, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *services.CardModel
	if rf, ok := ret.Get(0).(func(context.Context, kernel.Id) *services.CardModel); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.CardModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, kernel.Id) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveCard provides a mock function with given fields: _a0, _a1
func (_m *CardService) RemoveCard(_a0 context.Context, _a1 kernel.Id) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, kernel.Id) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCard provides a mock function with given fields: _a0, _a1
func (_m *CardService) UpdateCard(_a0 context.Context, _a1 *services.CardModel) (*services.CardModel, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *services.CardModel
	if rf, ok := ret.Get(0).(func(context.Context, *services.CardModel) *services.CardModel); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.CardModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *services.CardModel) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
